spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://49.232.228.221:3306/po_flysky?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver



#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#mybatis
mybatis:
  mapper-locations: classpath*:com/fly/sky/repository/*Mapper.xml

#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
