spring:
  datasource:
    username: root
    password: 11111111
    url: jdbc:mysql://localhost:3306/fly?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver



#showSql
logging:
  level:
    com:
      example:
        mapper : debug

#mybatis
mybatis:
  mapper-locations: classpath*:com/fly/sky/repository/*Mapper.xml

#配置分页插件pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
